# ~/.config/alacritty/alacritty.toml

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
bold.family   = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"
size = 12.0

[window]
padding.x = 8
padding.y = 8
decorations = "None"

[colors.primary]
foreground = "0xc8c093"
background = "0x202026"

[colors.normal]
black   = "0x16161d"
red     = "0xc34043"
green   = "0x76946a"
yellow  = "0xc0a36e"
blue    = "0x7e9cd8"
magenta = "0x957fb8"
cyan    = "0x6a9589"
white   = "0xc8c093"

[colors.bright]
black   = "0x727169"
red     = "0xe82424"
green   = "0x98bb6c"
yellow  = "0xe6c384"
blue    = "0x7fb4ca"
magenta = "0x938aa9"
cyan    = "0x7aa89f"
white   = "0xdcd7ba"
